version: "3"
services:

  services-es-x:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: services-es-x
    environment:
      - node.name=services-es-x
      - discovery.seed_hosts=services-es-x
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - services-data-x:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  services-kibana-x:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: services-kibana-x
    environment:
      ELASTICSEARCH_HOSTS: '["http://services-es-x:9200"]'
    ports:
      - 5601:5601
    depends_on:
      - services-es-x

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGO_DB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGO_DB_ADMINPASSWORD=password
      - ME_CONFIG_MONGO_DB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL="mongodb://admin:password@mongodb:27017"
    depends_on:
      - mongodb

networks:
  services:
    driver: bridge

volumes:
  services-data-x:
